version: '3.8'


services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - ./backend:/app

  mysql:
    image: mysql:8.0
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword    # Root password for MySQL
      MYSQL_DATABASE: FraudDetection       # Name of the database to create
      MYSQL_USER: username                 # Custom user
      MYSQL_PASSWORD: password             # Password for the custom user
    ports:
      - "3306:3306"                        # Map port 3306 on the host to port 3306 in the container
    volumes:
      # - mysql_data:/var/lib/mysql          # Persist database data
      - ./database/mysql-init:/docker-entrypoint-initdb.d # Initialize database scripts

volumes:
  mysql_data:
